### ISSUE TITLE
Smart-RSS handles http://xkcd.com/atom.xml OK but stopped handling http://xkcd.com/rss.xml

### ISSUE THREAD

**Issue by POTSandSTOP** [SmartRSS/Smart-RSS#119]
Atom feeds OK, RSS feeds seemed to have stopped being handled about two weeks ago.

**Comment by zakius** [comment]
Do you have both sources subscribed at the same time? I think the issue comes from both sources assigning the same GUID to items, as this scenario isn't common these items are seen as already loaded.

On my side there was no change in a way this situation is handled, possibly these GUIDs used to differ between Atom and RSS

I'lll consider handling this scenario but that won't be a quick fix, especially that I have issue with AMO to handle first

**Comment by POTSandSTOP** [comment]
> Do you have both sources subscribed at the same time?

Yes. They had been working fine since I installed Smart-RSS on April 9, 2020.

In case it helps, a similar extension that is no longer maintained, [Erinome RSS](https://chrome.google.com/webstore/detail/erinome-rss/jnepdmcgobemcmfcdobmiajiigncnmlc) is able to process http://xkcd.com/rss.xml just fine, even with both sources having been subscribed at the same time on April 9, 2020.
