### ISSUE TITLE
Feature request/bug report: SmartRSS requires improved accessibility for visually impaired users

### ISSUE THREAD

**Issue by amirsol81** [SmartRSS/Smart-RSS#132]
As a visually impaired Win 10/Chromium Edge user who relies on NVDA (the free and open-source screen reader for Windows), I can't make use of Smart RSS on MS Edge Chromium because the extension has accessibility issues. They can be summarized via the following:
1. The inability to bring up the Feed tree view via a keyboard shortcut. In Internet Explorer 11, this can be achieved by pressing Control+G. However, I can't find a way to bring up the tree view via keyboard shortcut in SmartRSS whenever desired.
2. The inability to move around RSS folders and single RSS feeds via the keyboard. I mean there's no way to move from one folder to its adjacent folder, up/down, via the keyboard. This is quite critical because without keyboard access, navigating the whole RSS tree for a quick summary becomes quite time-consuming. Sighted users of the extension see what's on the screen so they might not feel the need to move around the feed tree view easily. But visually impaired users need to be able to query the folder via the keyboard to figure out if their feeds have been updated.
3. The inability to bring up the context menu for the RSS tree view via the keyboard. Say you want to delete a folder, a single feed, or check the properties for an RSS feed. These can't be achieved via keyboard shortcuts -- or at least I can't understand how to perform them. In Internet Explorer 11, once you are in the feed tree view, you can press the Applications key to bring up the list of context menus to achieve all of these. As such, SmartRSS should provide a similar keyboard-driven functionality for the visually impaired. Even manually refreshing each feed should be accessible via the keyboard -- when we are in the RSS tree view.

Thanks.

**Comment by zakius** [comment]
Hello, thanks for your feedback

You can switch focus between panes using `shift+1` to select sources tree and `shift+2` to select articles list. Focusing content seems to be broken now so I'm noting this issue. When sources tree is active you can move the cursor with `up` and `down` arrows or `u` and `j` keys, pressing `right` arrow will display the list of articles of selected source while `enter` will do the same and move focus to the list. Unfortunately switching between sources encounters issues when folders are in use and closed, I'm noting this issue here. As a workaround you can use `ctrl+right` to expand all folders, in this state arrow navigation seems to be nearly perfect with the issue of view not scrolling when cursor moves out of viewport, noted. And when you select the folder you can toggle it's state with `left` arrow. As of the context menu there is no way to bring it up currently and I doubt it would be usable with keyboard input. Currently there is indeed no way to force refresh of a selected source from the sources panel, as a workaround you can press `enter` to activate articles list and then press `r` to refresh, but I am aware it is suboptimal.

I'm sorry for the issues you've encountered, I'll start slowly working on them and if you don't mind I'll be coming for your feedback from time to time. If you have any other issues feel free to report them. As a first question from my side: do you have any issues with the way content is presented? Do you feel like some pieces of information are missing or improperly reported?

**Comment by amirsol81** [comment]
@zakius Thanks a lot for your prompt reply. I'd be thrilled to help make Smart RSS more accessible as currently apart from the RSS reader built into Internet Explorer, no truly accessible RSS reader exists for Windows.
The most prominent issue I face when using Smart RSS is that NVDA, my Windows screen reader, tends to intercept most of the keys or shortcuts you suggested. Like other screen readers, it has its own "Browse mode" to interact with HTML content on web browsers and email clients. While we can ask it to ignore the next key press in order for it to be passed to the hosting app, and although we can disable "Browse mode" temporarily in order for "Focus mode" to control the hosting app on a more permanent basis, all of this back and forth will result in a less efficient and more time-consuming solution to interacting with Smart RSS, RSS folders/feeds, article content, etc. Granted, this is an issue affecting almost all MS Edge RSS readers I've tried, but at least Smart RSS has a more streamlined keyboard mapping at work, meaning we might be able to sort out many of the issues I reported.
As a solid first step, may I humbly suggest that you install NVDA to check some of these issues yourself in person? I'm sure compared with my reports, that will be a lot more helpful. NVDA can be downloaded from here: https://www.nvaccess.org/download/Please note that with NVDA active, Insert+F2 will pass the next key press to the hosting application, and Insert+Space will switch between "Browse mode" and "Focus mode" which I mentioned above.
At any event, with NVDA active -- and unless I'm missing something, it seems that navigation among folders and articles isn't possible. Or maybe navigation works but nothing gets announced -- similar to other announcements I get in other tree views. NVDA apparently treats the main Smart RSS window as an HTML page -- like any other browser tab, so I can see nothing which might resemble a classic tree view. Even if I press Insert+Space to activate the "Focus mode" in order to force NVDA to treat the Smart RSS window as a non-HTML window, keyboard navigation announces nothing to me -- even if it works which I'm not sure of.
Please let me know if I can be of any help -- even for alpha/beta-testing.
Thanks.

**Comment by zakius** [comment]
From my understanding making hotkeys configurable seems to be the most important step to make sure every hotkey is properly passed to reader. But in this case I'll need your feedback about settings interface once I build a prototype. I'll mention you in dedicated issue once I have something.

Fixing issues I mentioned here will also greatly improve your experience, especially the fact that moving the keyboard cursor across sources tree isn't announced at all, without this one you probably won't be able to use it. I'll look into it and see what can be done. Besides that I couldn't force article to be read and unfortunately many sources even don't contain full article which may be a big accessibility issue. Personally I just open original articles anyway but if you'd like to stay within reader I'd have to add option to load and parse original article on demand. To make it worse there is often no way to tell it isn't a full article in an automated way.

About testing: are you able to install Edge extensions from outside the store, is the process known to you and simple enough for you to go through it even few times a week for a fast feedback loop when I find the time to work on it?

**Comment by amirsol81** [comment]
@zakius Sure, I can install extensions from outside the store if required and will be happy to provide feedback.
I also tend to open original articles manually so the absence of full articles isn't important at all. The important points would be easy/vocalized navigation in the folder tree, easy/vocalized movement among folders, feeds inside folders, returning to the main tree, opening an article from inside the tree, easy returning to the folder, and being notified of the presence of new articles for each separate feed so that it can be acted upon. In Internet Explorer if a feed, or a folder containing a feed, contains new/unread articles, the word "new" gets added to the end of it: something like "CNET News (new)".
I might be stating the obvious, but currently most -- or all -- of this seem to be impossible or rather confusing with Smart RSS and a screen reader like NVDA.
Thanks.

**Comment by zakius** [comment]
Okay, I'll probably take a few days before I get anything done but I have another question then:

What you would consider *new*? Smart RSS tracks articles you glanced over and ones you marked as read (if I'm not mistaken it can be done automatically once you keep the article view open for specified time). So to reword this there are new articles, ones you already clicked but didn't mark them as read yet, ones marked as read. Then you can delete any of them to go away from articles list if it grows too big/article wasn't interesting in the slightest and you will never read it. Number of unread is displayed next to source name but isn't announced in any way either but this may not be what you need. Maybe I should track the number of articles found since the last time user opened specified source and use that to determine if there are any *new* ones?

If the way I state something is confusing feel free to ask, I'm pouring my train of thought here currently, being in brainstorming mode or something like that so some questions may have answers two sentences later.

**Comment by amirsol81** [comment]
@zakius Your contributions and suggestions are very much appreciated!
Well, I can think of the following:
1. Either the word "new" or the number indicating unread articles be added to the end of each folder, or each RSS feed if it's not in a folder. I suggest the simpler "new" word because I'm not sure if displaying the exact number or even keeping track of it would be easy or hassle-free.
2. What I've proposed is for navigation among folders or single feeds outside folders when the Article view hasn't been opened it. Once the Article view has been opened, the word "new" can be removed or, in the case of the number, that number indicator can be modified for the folder or feed.
3. The gist of all of these is that I want to be notified, one way or another, if refreshing the article list for a folder, or refreshing a single feed, has resulted in the discovery of new articles. So if you refresh all folders/feeds, or if an auto-refresh happens, you should be able to tell which folder or feed contains newly added articles upon navigating among them.
Thanks.

**Comment by zakius** [comment]
I'll be experimenting with notifications once I get navigation through sources tree properly announced, will let you know when I have something available to test

**Comment by amirsol81** [comment]
> I'll be experimenting with notifications once I get navigation through sources tree properly announced, will let you know when I have something available to test

Thanks for looking into the accessibility issues -- very much appreciated! 🌹💐

**Comment by amirsol81** [comment]
@zakius I brought up the topic of making Smart RSS accessible on NVDA's email list, and an interesting discussion ensued. A member even suggested to help with the coding. If you're interested, please kindly take a look: https://nvda.groups.io/g/nvda/topic/76063987#76166

**Comment by amirsol81** [comment]
@zakius Any news or developments regarding accessibility features and bug fixes discussed here? I'd be interested in testing them if something has been cooked so far.

**Comment by zakius** [comment]
I'm sorry, I've been pretty busy at work and haven't looked into it yet, I'll let you know as soon as I have something prepared

**Comment by amirsol81** [comment]
No problem at all -- do take your time.

**Comment by zakius** [comment]
Hello, sorry for long radio silence.

I just sat down to this issue and tried figuring some things out. Unfortunately it's a complete mess and it looks like it may be more than I can handle: in my browser of choice (Waterfox Classic, basically patched version of Firefox 56) nothing is announced at all, in Chromium based Edge articles list is announced when you move around with keyboard but feeds list isn't and I can't find any reason why it's the case. In Firefox Developer Edition the keyboard controls seem to be completely ignored and instead it sounds like accessibility layer takes over as it announces literally everything, one thing at a time, when I attempt to move around with keyboard, but without any visual indicators or affecting the in-app state of focus making it unusable with keyboard input.

As you may have noticed there are times when I'm really active on this project and times I can't find any willpower to do literally anything, unfortunately I'm out of it currently and while I would love to help you and possibly many others I have no idea how to tackle this issue. If you manage to get any tips I'll try to make use of them but it will be slow and painful process due to all that quirkiness.

I'm sorry for these bad news but that's all I can do as of now. If I happen to figure something out I'll let you know but currently I'm at a complete loss

**Comment by amirsol81** [comment]
Greetings. No problem at all. Thanks for spending time on that. 
Hopefully something might be done about it in the future.

**Comment by zakius** [comment]
As unfortunately I am unable to do anything with this issue and there is no community effort to work on it either I'm closing it as wontfix, though if someone in future decides to help I'll get back to it
