### ISSUE TITLE
Manual Sort Feeds

### ISSUE THREAD

**Issue by akizuha** [SmartRSS/Smart-RSS#170]
Currently all feeds and folders are sorted alphabetically. Would be great to have the ability to sort them manually, using drag and drop.

**Comment by zakius** [comment]
this requires much more effort than I can put into feature I won't use in the current state of things (see #167 )

**Comment by akizuha** [comment]
Is it really hard too implement this using something like `tree.jquery.js`? I do not know much about how browser add-on works, but I can contribute some frontend skills (HTML/XML/JS/CSS).

**Comment by zakius** [comment]
the code is ancient but frontend is jQuery free at this point, built on top of backbone.js

what would need to be done:
- performing action on drop of source obviously
- figuring out the new index of dragged element (the easiest part, that'd be index of target element)
- figuring out which elements should be modified
- updating all of these in the collection
- placing the element on the right place in DOM

and obviously some setting to choose which sorting should be used and ability to reset manual to the same as lexicographic

If you can do it I'll accept your PR, you don't need any special knowledge outside of basic frontend skills and backbone.js docs to achieve that for the most part

**Comment by akizuha** [comment]
I had a glance into the code. This `backbone.js` is really obscure compare to what I have done with mostly vanilla JavaScript before. And I seriously doubt is it even possible to integrate `tree.jquery.js` to it (for what I am understanding, `backbone.js` is kinda bind all DOM to a MVC framework, and jquery directly manipulate DOM without a view), or it can be really hard (at least for my skill) to implement a tree view with drag and drop in a MVC framework.

------------------------------------------------------------------------------------------
However I found more bugs during the investigation.
1. The current tree view has some issues after change the feed's folder. The padding and unread count are not adjusted. Only after restart the browser will correct this (Why refresh the page cannot???).
![1](https://user-images.githubusercontent.com/45957847/120060739-0a8e8980-c08c-11eb-88eb-f933fff55d5e.gif)
2. I believe it's leaking memory by refreshing the page in Chrome. And refresh the page in Firefox somehow close it?
![2](https://user-images.githubusercontent.com/45957847/120060742-0cf0e380-c08c-11eb-8449-884ddb18d2b5.gif)

**Comment by zakius** [comment]
there's no need to add any libraries to achieve this and it should be easier without that too

I've been working on folder change and it should work properly in most cases, haven't experienced issues with padding in a long time since bugfixes last year

as of counters I'm honestly not sure, I've been working on it recently but it should be in the latest version already, I can tell you why refreshing the view isn't enough though: it's merely displaying data from the background store that needs to be recalculated, if that fails the view can do nothing about it

as of refreshing: it generally shouldn't be used as the background initiates some tasks when clicking the button, additionally due to the way of communication Firefox sometimes garbage collects background script when closing the view so I resorted to forcing it to reload whole extension when closing the view, it's the best I was able to achieve and it just works, I'm not sure how well it behaves in Chrome, but as far as I can tell this one issue doesn't happen

**Comment by akizuha** [comment]
Feels super strange that it closes itself while refresh. Could it reloads while refresh instead of closing?
And it is possible to open multiple pages, and closing any of them results in others close themself too. Extremely weird.

**Comment by zakius** [comment]
there's really nothing I can do without porting the whole communication between view and background to messages, that's the best workaround I could find, without reloading the whole extension background store gets collected and everything starts falling apart, it may not happen with small collections but the more sources and articles you have the more likely it is to break

**Comment by zakius** [comment]
https://github.com/bevacqua/dragula dropping it here for reference but I still think it's unlikely I'll do it
