### ISSUE TITLE
Some older articles are shown as unread after being read.

### ISSUE THREAD

**Issue by ForgetfulWasAria** [SmartRSS/Smart-RSS#181]
Certain older articles are showing as unread since the recent updates. Marking them as read lasts only until Smart-RSS refreshes articles. Not all articles are affected but certain feeds will consistently show the same number of unread items.

I'm on Windows 10 with Firefox 91. I have tried:
restarting the browser
exporting my feeds to smart-rss format, removing the extension, then re-adding it.

This sounds like https://github.com/SmartRSS/Smart-RSS/issues/180 but is occurring after the update you posted yesterday.
Thank you!

**Comment by zakius** [comment]
can you make sure you have 2.23.1 already installed? autoupdate interval can take even few days so if you got 2.23.0 installed automatically it'll take some time before your browser checks for updates again, the version number is displayed in settings

if it's not you can force update check in extensions manager from menu under cog wheel if I remember correctly, if it is can you provide sample of at least one feed that has this issue? preferably as code due to ever changing nature of feeds

**Comment by ForgetfulWasAria** [comment]
Yes, the config page shows 2.23.1. I'm not sure if you mean the HTML code from the inspector or something else, sorry. This feed is showing the problem and it's only updated every few weeks:
[Order of the Stick](https://www.giantitp.com/comics/oots.rss)

[NPR](http://www.npr.org/rss/rss.php) is also doing the same thing.

**Comment by zakius** [comment]
okay, I'll take a look at this, sorry for the trouble

**Comment by zakius** [comment]
Okay, for the first one it's technically issue with the feed as it doesn't provide item dates, but I'll try figuring something out, for the second I can't access this address at all

**Comment by ForgetfulWasAria** [comment]
Thanks for looking into this. I understand that non-standard feeds are going to be hard to support.
