### ISSUE TITLE
Tolerate slightly non-standard RSS feeds

### ISSUE THREAD

**Issue by Qrox** [SmartRSS/Smart-RSS#213]
This is not a SmartRSS issue per se, but it would be nice to tolerate certain non-standard RSS feeds that do not interfere with their correct parsing, such as those with extra elements alongside the rss element. An example is https://retractionwatch.com/feed/, where an additional line of error message is appended to the file. I've contacted the site and they said the feed was working fine in Feedly, so it would also be nice to have feature parity with other feed softwares.

**Comment by zakius** [comment]
non-standard feeds are handled pretty well, as long as they are valid XML at least - parser looks for all possible tags and attributes, no matter which format is announced in link, response header, stated in filename or in the document header, but for invalid XML there isn't much that can be done without severely increasing code complexity and likely creating separate hacks for every encountered issues

considering that and the fact this project is basically in maintenance mode due to #167 I can't afford to put that much effort into this

to be perfectly honest forcing this feed to work would be pretty simple task, though that's a dangerous precedence I'm not willing to make at this moment, I'm sorry
